[[redirects]]
  from = "/.well-known/acme-challenge/z--BUe2ud4KD-KuEqm-RuyOF6oQT16LQHRzvGymldx0.V4RcF3cJlbKIu0ePrZBscU44993YREiiblAhLPy9Ecw"
  to = "/acme-challenge"
  status = 200

# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[build]
  command = "yarn build && mkdir -p build/.well-known/acme-challenge/ && echo \"z--BUe2ud4KD-KuEqm-RuyOF6oQT16LQHRzvGymldx0.V4RcF3cJlbKIu0ePrZBscU44993YREiiblAhLPy9Ecw\" > ./build/acme-challenge"