[[redirects]]
  from = "/.well-known/acme-challenge/V4RcF3cJlbKIu0ePrZBscU44993YREiiblAhLPy9Ecw"
  to = "/.well-known/acme-challenge/V4RcF3cJlbKIu0ePrZBscU44993YREiiblAhLPy9Ecw"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "yarn build && mkdir -p build/.well-known/acme-challenge/ && echo \"xOqtlJas47G9sMlw91ZGRFfS5QVNDrWWteNdnTGAzm8.V4RcF3cJlbKIu0ePrZBscU44993YREiiblAhLPy9Ecw\" > ./build/.well-known/acme-challenge/xOqtlJas47G9sMlw91ZGRFfS5QVNDrWWteNdnTGAzm8"